language: cpp
dist: bionic
compiler: gcc

before_install:
  - sudo apt-get update -qq

install: 
  # C++14
  - sudo apt-get install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq libqt5webkit5-dev qtdeclarative5-dev libqt5svg5*
  - export QMAKE=/usr/lib/x86_64-linux-gnu/qt5/bin/qmake
  # QtSvg
  - sudo apt-get install libqt5svg5-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh
  # Other prerequisites
  - ./download_other_githubs

services:
  - xvfb

script: 
  # Build and run test
  - qmake -qt=qt5 QtKeyboardFriendlyGraphicsViewTest.pro
  - make --silent debug
  - ./QtKeyboardFriendlyGraphicsViewTest
  # Build and run and kill demo
  - qmake -qt=qt5 QtKeyboardFriendlyGraphicsViewDemoDesktop.pro
  - make --silent debug
  - ./QtKeyboardFriendlyGraphicsViewDemoDesktop &
  - sleep 10
  - sudo killall -9 QtKeyboardFriendlyGraphicsViewDemoDesktop
  # cppcheck
  - cppcheck --quiet --error-exitcode=1 . 
  # Get code coverage
  - ./get_code_cov >/dev/null
  - codecov
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
